WITH TBL_VIDEO AS (
    SELECT
        (CASE WHEN T.MPAA_RATE = 'G' THEN TITLE ELSE NULL END) AS 'G',
            (CASE WHEN T.MPAA_RATE = 'PG' THEN TITLE ELSE NULL END) AS 'PG',
            (CASE WHEN T.MPAA_RATE = 'PG-13' THEN TITLE ELSE NULL END) AS 'PG-13',
            (CASE WHEN T.MPAA_RATE = 'R' THEN TITLE ELSE NULL END) AS 'R',
            (CASE WHEN T.MPAA_RATE = 'NC-17' THEN TITLE ELSE NULL END) AS 'NC-17',
            RANKING
    FROM (
             SELECT
                 V.TITLE,
                 V.MPAA_RATE,
                 RANK() OVER (PARTITION BY V.MPAA_RATE ORDER BY V.MPAA_RATE ASC, V.RATE DESC, V.TITLE ASC) AS RANKING
             FROM VIDEOS V
             ORDER BY FIELD(V.MPAA_RATE, 'G', 'PG', 'PG-13', 'R', 'NC-17'), V.RATE DESC, V.TITLE ASC
         ) T
)
SELECT
    IFNULL(G, 0) AS G, IFNULL(PG, 0) AS PG, IFNULL(`PG-13`, 0) AS `PG-13`, IFNULL(R, 0) AS R, IFNULL(`NC-17`, 0) AS `NC-17`
FROM (
         SELECT IFNULL(R, 0) AS R, RANKING
         FROM TBL_VIDEO T
         WHERE T.R IS NOT NULL
     ) TMP1
         LEFT OUTER JOIN (
    SELECT IFNULL(PG, 0) AS PG, RANKING
    FROM TBL_VIDEO T
    WHERE T.PG IS NOT NULL
) TMP2
                         ON TMP1.RANKING = TMP2.RANKING
         LEFT OUTER JOIN (
    SELECT IFNULL(`PG-13`, 0) AS `PG-13`, RANKING
    FROM TBL_VIDEO T
    WHERE T.`PG-13` IS NOT NULL
) TMP3
                         ON TMP2.RANKING = TMP3.RANKING
         LEFT OUTER JOIN (
    SELECT IFNULL(G, 0) AS G, RANKING
    FROM TBL_VIDEO T
    WHERE T.G IS NOT NULL
) TMP4
                         ON TMP3.RANKING = TMP4.RANKING
         LEFT OUTER JOIN (
    SELECT IFNULL(`NC-17`, 0) AS `NC-17`, RANKING
    FROM TBL_VIDEO T
    WHERE T.`NC-17` IS NOT NULL
) TMP5
                         ON TMP4.RANKING = TMP5.RANKING